development:
  adapter: postgresql
  encoding: unicode
  database: vpeeker-channels_development

test:
  adapter: postgresql
  encoding: unicode
  database: vpeeker-channels_test

production:
  adapter: postgresql
  encoding: unicode
  database: vpeeker-channels_production
